/* generated by the conformance suite from JSONTestSuite 1ef36fa,
   https://github.com/nst/JSONTestSuite (MIT license,
   see JSONTestSuite.LICENSE); do not edit */

#ifndef ASKL_JSONTESTSUITE_H

#define ASKL_JSONTESTSUITE_H

typedef struct JSON_Fixture {
    const char *name;
    char class;      /* y: valid, n: invalid, i: implementation defined */
    char verdict;    /* pinned tokenizer verdict, '-' if not pinned */
    char parsed;     /* same, with the parser context */
    const char *pattern;
    size_t plen;
    unsigned int repeat;
    const char *tail;
    size_t tlen;
} JSON_Fixture;

#define JSONTESTSUITE_COMMIT "1ef36fa"

static const JSON_Fixture _jsontestsuite[] = {
    {
        "i_number_double_huge_neg_exp", 'i', 'A', 'A',
        "[123.456e-789]"
        , 14, 1,
        ""
        , 0
    },
    {
        "i_number_huge_exp", 'i', 'A', 'R',
        "[0.4e006699999999999999999999999999999999999999999999999999999999999"
        "99999999999999999999999999999999999999999999999999999999969999999006"
        "]"
        , 137, 1,
        ""
        , 0
    },
    {
        "i_number_neg_int_huge_exp", 'i', 'A', 'R',
        "[-1e+9999]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_number_pos_double_huge_exp", 'i', 'A', 'R',
        "[1.5e+9999]"
        , 11, 1,
        ""
        , 0
    },
    {
        "i_number_real_neg_overflow", 'i', 'A', 'R',
        "[-123123e100000]"
        , 16, 1,
        ""
        , 0
    },
    {
        "i_number_real_pos_overflow", 'i', 'A', 'R',
        "[123123e100000]"
        , 15, 1,
        ""
        , 0
    },
    {
        "i_number_real_underflow", 'i', 'A', 'A',
        "[123e-10000000]"
        , 15, 1,
        ""
        , 0
    },
    {
        "i_number_too_big_neg_int", 'i', 'A', 'A',
        "[-123123123123123123123123123123]"
        , 33, 1,
        ""
        , 0
    },
    {
        "i_number_too_big_pos_int", 'i', 'A', 'A',
        "[100000000000000000000]"
        , 23, 1,
        ""
        , 0
    },
    {
        "i_number_very_big_negative_int", 'i', 'A', 'A',
        "[-237462374673276894279832749832423479823246327846]"
        , 51, 1,
        ""
        , 0
    },
    {
        "i_object_key_lone_2nd_surrogate", 'i', 'A', 'R',
        "{\"\\uDFAA\":0}"
        , 12, 1,
        ""
        , 0
    },
    {
        "i_string_1st_surrogate_but_2nd_missing", 'i', 'A', 'R',
        "[\"\\uDADA\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_1st_valid_surrogate_2nd_invalid", 'i', 'A', 'R',
        "[\"\\uD888\\u1234\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "i_string_UTF-16LE_with_BOM", 'i', 'R', 'R',
        "\377\376[\000\"\000\351\000\"\000]\000"
        , 12, 1,
        ""
        , 0
    },
    {
        "i_string_UTF-8_invalid_sequence", 'i', 'A', 'R',
        "[\"\346\227\245\321\210\372\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_UTF8_surrogate_U+D800", 'i', 'A', 'R',
        "[\"\355\240\200\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "i_string_incomplete_surrogate_and_escape_valid", 'i', 'A', 'R',
        "[\"\\uD800\\n\"]"
        , 12, 1,
        ""
        , 0
    },
    {
        "i_string_incomplete_surrogate_pair", 'i', 'A', 'R',
        "[\"\\uDd1ea\"]"
        , 11, 1,
        ""
        , 0
    },
    {
        "i_string_incomplete_surrogates_escape_valid", 'i', 'A', 'R',
        "[\"\\uD800\\uD800\\n\"]"
        , 18, 1,
        ""
        , 0
    },
    {
        "i_string_invalid_lonely_surrogate", 'i', 'A', 'R',
        "[\"\\ud800\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_invalid_surrogate", 'i', 'A', 'R',
        "[\"\\ud800abc\"]"
        , 13, 1,
        ""
        , 0
    },
    {
        "i_string_invalid_utf-8", 'i', 'A', 'R',
        "[\"\377\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "i_string_inverted_surrogates_U+1D11E", 'i', 'A', 'R',
        "[\"\\uDd1e\\uD834\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "i_string_iso_latin_1", 'i', 'A', 'R',
        "[\"\351\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "i_string_lone_second_surrogate", 'i', 'A', 'R',
        "[\"\\uDFAA\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_lone_utf8_continuation_byte", 'i', 'A', 'R',
        "[\"\201\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "i_string_not_in_unicode_range", 'i', 'A', 'R',
        "[\"\364\277\277\277\"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "i_string_overlong_sequence_2_bytes", 'i', 'A', 'R',
        "[\"\300\257\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "i_string_overlong_sequence_6_bytes", 'i', 'A', 'R',
        "[\"\374\203\277\277\277\277\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_overlong_sequence_6_bytes_null", 'i', 'A', 'R',
        "[\"\374\200\200\200\200\200\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_truncated-utf-8", 'i', 'A', 'R',
        "[\"\340\377\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "i_string_utf16BE_no_BOM", 'i', 'R', 'R',
        "\000[\000\"\000\351\000\"\000]"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_string_utf16LE_no_BOM", 'i', 'R', 'R',
        "[\000\"\000\351\000\"\000]\000"
        , 10, 1,
        ""
        , 0
    },
    {
        "i_structure_500_nested_arrays", 'i', 'A', 'A',
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[["
        "[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        "]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]"
        , 1000, 1,
        ""
        , 0
    },
    {
        "i_structure_UTF-8_BOM_empty_object", 'i', 'A', 'A',
        "\357\273\277{}"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_array_1_true_without_comma", 'n', 'R', 'R',
        "[1 true]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_array_a_invalid_utf8", 'n', 'R', 'R',
        "[a\345]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_array_colon_instead_of_comma", 'n', 'R', 'R',
        "[\"\": 1]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_array_comma_after_close", 'n', 'R', 'T',
        "[\"\"],"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_array_comma_and_number", 'n', 'R', 'R',
        "[,1]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_array_double_comma", 'n', 'R', 'R',
        "[1,,2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_array_double_extra_comma", 'n', 'R', 'R',
        "[\"x\",,]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_array_extra_close", 'n', 'R', 'T',
        "[\"x\"]]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_array_extra_comma", 'n', 'R', 'R',
        "[\"\",]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_array_incomplete", 'n', 'I', 'I',
        "[\"x\""
        , 4, 1,
        ""
        , 0
    },
    {
        "n_array_incomplete_invalid_value", 'n', 'R', 'R',
        "[x"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_array_inner_array_no_comma", 'n', 'R', 'R',
        "[3[4]]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_array_invalid_utf8", 'n', 'R', 'R',
        "[\377]"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_items_separated_by_semicolon", 'n', 'R', 'R',
        "[1:2]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_array_just_comma", 'n', 'R', 'R',
        "[,]"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_just_minus", 'n', 'R', 'R',
        "[-]"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_missing_value", 'n', 'R', 'R',
        "[   , \"\"]"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_array_newlines_unclosed", 'n', 'I', 'I',
        "[\"a\",\0124\012,1,"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_array_number_and_comma", 'n', 'R', 'R',
        "[1,]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_array_number_and_several_commas", 'n', 'R', 'R',
        "[1,,]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_array_spaces_vertical_tab_formfeed", 'n', 'R', 'R',
        "[\"\013a\"\\f]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_array_star_inside", 'n', 'R', 'R',
        "[*]"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_unclosed", 'n', 'I', 'I',
        "[\"\""
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_unclosed_trailing_comma", 'n', 'I', 'I',
        "[1,"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_array_unclosed_with_new_lines", 'n', 'I', 'I',
        "[1,\0121\012,1"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_array_unclosed_with_object_inside", 'n', 'I', 'I',
        "[{}"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_incomplete_false", 'n', 'R', 'R',
        "[fals]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_incomplete_null", 'n', 'R', 'R',
        "[nul]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_incomplete_true", 'n', 'R', 'R',
        "[tru]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_multidigit_number_then_00", 'n', 'R', 'R',
        "123\000"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_number_++", 'n', 'R', 'R',
        "[++1234]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_number_+1", 'n', 'R', 'R',
        "[+1]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_number_+Inf", 'n', 'R', 'R',
        "[+Inf]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_-01", 'n', 'R', 'R',
        "[-01]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_-1.0.", 'n', 'R', 'R',
        "[-1.0.]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_-2.", 'n', 'R', 'R',
        "[-2.]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_-NaN", 'n', 'R', 'R',
        "[-NaN]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_.-1", 'n', 'R', 'R',
        "[.-1]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_.2e-3", 'n', 'R', 'R',
        "[.2e-3]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_0.1.2", 'n', 'R', 'R',
        "[0.1.2]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_0.3e+", 'n', 'R', 'R',
        "[0.3e+]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_0.3e", 'n', 'R', 'R',
        "[0.3e]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_0.e1", 'n', 'R', 'R',
        "[0.e1]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_0_capital_E+", 'n', 'R', 'R',
        "[0E+]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_0_capital_E", 'n', 'R', 'R',
        "[0E]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_number_0e+", 'n', 'R', 'R',
        "[0e+]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_0e", 'n', 'R', 'R',
        "[0e]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_number_1.0e+", 'n', 'R', 'R',
        "[1.0e+]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_1.0e-", 'n', 'R', 'R',
        "[1.0e-]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_1.0e", 'n', 'R', 'R',
        "[1.0e]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_1_000", 'n', 'R', 'R',
        "[1 000.0]"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_number_1eE2", 'n', 'R', 'R',
        "[1eE2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_2.e+3", 'n', 'R', 'R',
        "[2.e+3]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_2.e-3", 'n', 'R', 'R',
        "[2.e-3]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_2.e3", 'n', 'R', 'R',
        "[2.e3]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_9.e+", 'n', 'R', 'R',
        "[9.e+]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_Inf", 'n', 'R', 'R',
        "[Inf]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_NaN", 'n', 'R', 'R',
        "[NaN]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_U+FF11_fullwidth_digit_one", 'n', 'R', 'R',
        "[\357\274\221]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_expression", 'n', 'R', 'R',
        "[1+2]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_hex_1_digit", 'n', 'R', 'R',
        "[0x1]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_hex_2_digits", 'n', 'R', 'R',
        "[0x42]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_infinity", 'n', 'R', 'R',
        "[Infinity]"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_number_invalid+-", 'n', 'R', 'R',
        "[0e+-1]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_invalid-negative-real", 'n', 'R', 'R',
        "[-123.123foo]"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_number_invalid-utf-8-in-bigger-int", 'n', 'R', 'R',
        "[123\345]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_invalid-utf-8-in-exponent", 'n', 'R', 'R',
        "[1e1\345]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_invalid-utf-8-in-int", 'n', 'R', 'R',
        "[0\345]\012"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_minus_infinity", 'n', 'R', 'R',
        "[-Infinity]"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_number_minus_sign_with_trailing_garbage", 'n', 'R', 'R',
        "[-foo]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_minus_space_1", 'n', 'R', 'R',
        "[- 1]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_neg_int_starting_with_zero", 'n', 'R', 'R',
        "[-012]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_neg_real_without_int_part", 'n', 'R', 'R',
        "[-.123]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_number_neg_with_garbage_at_end", 'n', 'R', 'R',
        "[-1x]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_real_garbage_after_e", 'n', 'R', 'R',
        "[1ea]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_real_with_invalid_utf8_after_e", 'n', 'R', 'R',
        "[1e\345]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_number_real_without_fractional_part", 'n', 'R', 'R',
        "[1.]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_number_starting_with_dot", 'n', 'R', 'R',
        "[.123]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_number_with_alpha", 'n', 'R', 'R',
        "[1.2a-3]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_number_with_alpha_char", 'n', 'R', 'R',
        "[1.8011670033376514H-308]"
        , 25, 1,
        ""
        , 0
    },
    {
        "n_number_with_leading_zero", 'n', 'R', 'R',
        "[012]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_object_bad_value", 'n', 'R', 'R',
        "[\"x\", truth]"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_object_bracket_key", 'n', 'R', 'R',
        "{[: \"x\"}\012"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_object_comma_instead_of_colon", 'n', 'R', 'R',
        "{\"x\", null}"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_object_double_colon", 'n', 'R', 'R',
        "{\"x\"::\"b\"}"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_object_emoji", 'n', 'R', 'R',
        "{\360\237\207\250\360\237\207\255}"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_object_garbage_at_end", 'n', 'R', 'R',
        "{\"a\":\"a\" 123}"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_object_key_with_single_quotes", 'n', 'R', 'R',
        "{key: 'value'}"
        , 14, 1,
        ""
        , 0
    },
    {
        "n_object_lone_continuation_byte_in_key_and_trailing_comma", 'n', 'R', 'R',
        "{\"\271\":\"0\",}"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_object_missing_colon", 'n', 'R', 'R',
        "{\"a\" b}"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_object_missing_key", 'n', 'R', 'R',
        "{:\"b\"}"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_object_missing_semicolon", 'n', 'R', 'R',
        "{\"a\" \"b\"}"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_object_missing_value", 'n', 'I', 'I',
        "{\"a\":"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_object_no-colon", 'n', 'I', 'I',
        "{\"a\""
        , 4, 1,
        ""
        , 0
    },
    {
        "n_object_non_string_key", 'n', 'R', 'R',
        "{1:1}"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_object_non_string_key_but_huge_number_instead", 'n', 'R', 'R',
        "{9999E9999:1}"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_object_repeated_null_null", 'n', 'R', 'R',
        "{null:null,null:null}"
        , 21, 1,
        ""
        , 0
    },
    {
        "n_object_several_trailing_commas", 'n', 'R', 'R',
        "{\"id\":0,,,,,}"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_object_single_quote", 'n', 'R', 'R',
        "{'a':0}"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_object_trailing_comma", 'n', 'R', 'R',
        "{\"id\":0,}"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_object_trailing_comment", 'n', 'R', 'T',
        "{\"a\":\"b\"}/**/"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_object_trailing_comment_open", 'n', 'R', 'T',
        "{\"a\":\"b\"}/**//"
        , 14, 1,
        ""
        , 0
    },
    {
        "n_object_trailing_comment_slash_open", 'n', 'R', 'T',
        "{\"a\":\"b\"}//"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_object_trailing_comment_slash_open_incomplete", 'n', 'R', 'T',
        "{\"a\":\"b\"}/"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_object_two_commas_in_a_row", 'n', 'R', 'R',
        "{\"a\":\"b\",,\"c\":\"d\"}"
        , 18, 1,
        ""
        , 0
    },
    {
        "n_object_unquoted_key", 'n', 'R', 'R',
        "{a: \"b\"}"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_object_unterminated-value", 'n', 'I', 'I',
        "{\"a\":\"a"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_object_with_single_string", 'n', 'R', 'R',
        "{ \"foo\" : \"bar\", \"a\" }"
        , 22, 1,
        ""
        , 0
    },
    {
        "n_object_with_trailing_garbage", 'n', 'R', 'T',
        "{\"a\":\"b\"}#"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_single_space", 'n', 'E', 'E',
        " "
        , 1, 1,
        ""
        , 0
    },
    {
        "n_string_1_surrogate_then_escape", 'n', 'I', 'I',
        "[\"\\uD800\\\"]"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_string_1_surrogate_then_escape_u", 'n', 'R', 'R',
        "[\"\\uD800\\u\"]"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_string_1_surrogate_then_escape_u1", 'n', 'R', 'R',
        "[\"\\uD800\\u1\"]"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_string_1_surrogate_then_escape_u1x", 'n', 'R', 'R',
        "[\"\\uD800\\u1x\"]"
        , 14, 1,
        ""
        , 0
    },
    {
        "n_string_accentuated_char_no_quotes", 'n', 'R', 'R',
        "[\303\251]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_string_backslash_00", 'n', 'R', 'R',
        "[\"\\\000\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_string_escape_x", 'n', 'R', 'R',
        "[\"\\x00\"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_string_escaped_backslash_bad", 'n', 'I', 'I',
        "[\"\\\\\\\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_string_escaped_ctrl_char_tab", 'n', 'R', 'R',
        "[\"\\\011\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_string_escaped_emoji", 'n', 'R', 'R',
        "[\"\\\360\237\214\200\"]"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_string_incomplete_escape", 'n', 'I', 'I',
        "[\"\\\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_string_incomplete_escaped_character", 'n', 'R', 'R',
        "[\"\\u00A\"]"
        , 9, 1,
        ""
        , 0
    },
    {
        "n_string_incomplete_surrogate", 'n', 'R', 'R',
        "[\"\\uD834\\uDd\"]"
        , 14, 1,
        ""
        , 0
    },
    {
        "n_string_incomplete_surrogate_escape_invalid", 'n', 'R', 'R',
        "[\"\\uD800\\uD800\\x\"]"
        , 18, 1,
        ""
        , 0
    },
    {
        "n_string_invalid-utf-8-in-escape", 'n', 'R', 'R',
        "[\"\\u\345\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_string_invalid_backslash_esc", 'n', 'R', 'R',
        "[\"\\a\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_string_invalid_unicode_escape", 'n', 'R', 'R',
        "[\"\\uqqqq\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_string_invalid_utf8_after_escape", 'n', 'R', 'R',
        "[\"\\\345\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_string_leading_uescaped_thinspace", 'n', 'R', 'R',
        "[\\u0020\"asd\"]"
        , 13, 1,
        ""
        , 0
    },
    {
        "n_string_no_quotes_with_bad_escape", 'n', 'R', 'R',
        "[\\n]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_string_single_doublequote", 'n', 'E', 'E',
        "\""
        , 1, 1,
        ""
        , 0
    },
    {
        "n_string_single_quote", 'n', 'R', 'R',
        "['single quote']"
        , 16, 1,
        ""
        , 0
    },
    {
        "n_string_single_string_no_double_quotes", 'n', 'R', 'R',
        "abc"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_string_start_escape_unclosed", 'n', 'I', 'I',
        "[\"\\"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_string_unescaped_ctrl_char", 'n', 'R', 'R',
        "[\"a\000a\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "n_string_unescaped_newline", 'n', 'R', 'R',
        "[\"new\012line\"]"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_string_unescaped_tab", 'n', 'R', 'R',
        "[\"\011\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_string_unicode_CapitalU", 'n', 'R', 'R',
        "\"\\UA66D\""
        , 8, 1,
        ""
        , 0
    },
    {
        "n_string_with_trailing_garbage", 'n', 'R', 'T',
        "\"\"x"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_100000_opening_arrays", 'n', 'I', 'R',
        "["
        , 1, 100000,
        ""
        , 0
    },
    {
        "n_structure_U+2060_word_joined", 'n', 'R', 'R',
        "[\342\201\240]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_structure_UTF8_BOM_no_data", 'n', 'E', 'E',
        "\357\273\277"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_angle_bracket_.", 'n', 'R', 'R',
        "<.>"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_angle_bracket_null", 'n', 'R', 'R',
        "[<null>]"
        , 8, 1,
        ""
        , 0
    },
    {
        "n_structure_array_trailing_garbage", 'n', 'R', 'T',
        "[1]x"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_array_with_extra_array_close", 'n', 'R', 'T',
        "[1]]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_array_with_unclosed_string", 'n', 'I', 'I',
        "[\"asd]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_structure_ascii-unicode-identifier", 'n', 'R', 'R',
        "a\303\245"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_capitalized_True", 'n', 'R', 'R',
        "[True]"
        , 6, 1,
        ""
        , 0
    },
    {
        "n_structure_close_unopened_array", 'n', 'R', 'R',
        "1]"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_comma_instead_of_closing_brace", 'n', 'I', 'I',
        "{\"x\": true,"
        , 11, 1,
        ""
        , 0
    },
    {
        "n_structure_double_array", 'n', 'T', 'T',
        "[][]"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_end_array", 'n', 'R', 'R',
        "]"
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_incomplete_UTF8_BOM", 'n', 'R', 'R',
        "\357\273{}"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_lone-invalid-utf-8", 'n', 'R', 'R',
        "\345"
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_lone-open-bracket", 'n', 'I', 'I',
        "["
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_no_data", 'n', 'E', 'E',
        ""
        , 0, 1,
        ""
        , 0
    },
    {
        "n_structure_null-byte-outside-string", 'n', 'R', 'R',
        "[\000]"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_number_with_trailing_garbage", 'n', 'R', 'R',
        "2@"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_object_followed_by_closing_object", 'n', 'R', 'T',
        "{}}"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_object_unclosed_no_value", 'n', 'I', 'I',
        "{\"\":"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_object_with_comment", 'n', 'R', 'R',
        "{\"a\":/*comment*/\"b\"}"
        , 20, 1,
        ""
        , 0
    },
    {
        "n_structure_object_with_trailing_garbage", 'n', 'T', 'T',
        "{\"a\": true} \"x\""
        , 15, 1,
        ""
        , 0
    },
    {
        "n_structure_open_array_apostrophe", 'n', 'R', 'R',
        "['"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_array_comma", 'n', 'R', 'R',
        "[,"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_array_object", 'n', 'I', 'R',
        "[{\"\":"
        , 5, 50000,
        "\012"
        , 1
    },
    {
        "n_structure_open_array_open_object", 'n', 'I', 'I',
        "[{"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_array_open_string", 'n', 'I', 'I',
        "[\"a"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_open_array_string", 'n', 'I', 'I',
        "[\"a\""
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object", 'n', 'I', 'I',
        "{"
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object_close_array", 'n', 'R', 'R',
        "{]"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object_comma", 'n', 'R', 'R',
        "{,"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object_open_array", 'n', 'R', 'R',
        "{["
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object_open_string", 'n', 'I', 'I',
        "{\"a"
        , 3, 1,
        ""
        , 0
    },
    {
        "n_structure_open_object_string_with_apostrophes", 'n', 'R', 'R',
        "{'a'"
        , 4, 1,
        ""
        , 0
    },
    {
        "n_structure_open_open", 'n', 'R', 'R',
        "[\"\\{[\"\\{[\"\\{[\"\\{"
        , 16, 1,
        ""
        , 0
    },
    {
        "n_structure_single_eacute", 'n', 'R', 'R',
        "\351"
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_single_star", 'n', 'R', 'R',
        "*"
        , 1, 1,
        ""
        , 0
    },
    {
        "n_structure_trailing_#", 'n', 'R', 'T',
        "{\"a\":\"b\"}#{}"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_structure_uescaped_LF_before_string", 'n', 'R', 'R',
        "[\\u000A\"\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "n_structure_unclosed_array", 'n', 'I', 'I',
        "[1"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_unclosed_array_partial_null", 'n', 'I', 'I',
        "[ false, nul"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_structure_unclosed_array_unfinished_false", 'n', 'I', 'I',
        "[ true, fals"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_structure_unclosed_array_unfinished_true", 'n', 'I', 'I',
        "[ false, tru"
        , 12, 1,
        ""
        , 0
    },
    {
        "n_structure_unclosed_object", 'n', 'I', 'I',
        "{\"asd\":\"asd\""
        , 12, 1,
        ""
        , 0
    },
    {
        "n_structure_unicode-identifier", 'n', 'R', 'R',
        "\303\245"
        , 2, 1,
        ""
        , 0
    },
    {
        "n_structure_whitespace_U+2060_word_joiner", 'n', 'R', 'R',
        "[\342\201\240]"
        , 5, 1,
        ""
        , 0
    },
    {
        "n_structure_whitespace_formfeed", 'n', 'R', 'R',
        "[\014]"
        , 3, 1,
        ""
        , 0
    },
    {
        "y_array_arraysWithSpaces", 'y', 'A', 'A',
        "[[]   ]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_array_empty-string", 'y', 'A', 'A',
        "[\"\"]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_array_empty", 'y', 'A', 'A',
        "[]"
        , 2, 1,
        ""
        , 0
    },
    {
        "y_array_ending_with_newline", 'y', 'A', 'A',
        "[\"a\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "y_array_false", 'y', 'A', 'A',
        "[false]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_array_heterogeneous", 'y', 'A', 'A',
        "[null, 1, \"1\", {}]"
        , 18, 1,
        ""
        , 0
    },
    {
        "y_array_null", 'y', 'A', 'A',
        "[null]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_array_with_1_and_newline", 'y', 'A', 'A',
        "[1\012]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_array_with_leading_space", 'y', 'A', 'A',
        " [1]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_array_with_several_null", 'y', 'A', 'A',
        "[1,null,null,null,2]"
        , 20, 1,
        ""
        , 0
    },
    {
        "y_array_with_trailing_space", 'y', 'A', 'A',
        "[2] "
        , 4, 1,
        ""
        , 0
    },
    {
        "y_number", 'y', 'A', 'A',
        "[123e65]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_number_0e+1", 'y', 'A', 'A',
        "[0e+1]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_0e1", 'y', 'A', 'A',
        "[0e1]"
        , 5, 1,
        ""
        , 0
    },
    {
        "y_number_after_space", 'y', 'A', 'A',
        "[ 4]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_number_double_close_to_zero", 'y', 'A', 'A',
        "[-0.0000000000000000000000000000000000000000000000000000000000000000"
        "00000000000001]\012"
        , 84, 1,
        ""
        , 0
    },
    {
        "y_number_int_with_exp", 'y', 'A', 'A',
        "[20e1]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_minus_zero", 'y', 'A', 'A',
        "[-0]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_number_negative_int", 'y', 'A', 'A',
        "[-123]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_negative_one", 'y', 'A', 'A',
        "[-1]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_number_negative_zero", 'y', 'A', 'A',
        "[-0]"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_number_real_capital_e", 'y', 'A', 'A',
        "[1E22]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_real_capital_e_neg_exp", 'y', 'A', 'A',
        "[1E-2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_real_capital_e_pos_exp", 'y', 'A', 'A',
        "[1E+2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_real_exponent", 'y', 'A', 'A',
        "[123e45]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_number_real_fraction_exponent", 'y', 'A', 'A',
        "[123.456e78]"
        , 12, 1,
        ""
        , 0
    },
    {
        "y_number_real_neg_exp", 'y', 'A', 'A',
        "[1e-2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_real_pos_exponent", 'y', 'A', 'A',
        "[1e+2]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_number_simple_int", 'y', 'A', 'A',
        "[123]"
        , 5, 1,
        ""
        , 0
    },
    {
        "y_number_simple_real", 'y', 'A', 'A',
        "[123.456789]"
        , 12, 1,
        ""
        , 0
    },
    {
        "y_object", 'y', 'A', 'A',
        "{\"asd\":\"sdf\", \"dfg\":\"fgh\"}"
        , 26, 1,
        ""
        , 0
    },
    {
        "y_object_basic", 'y', 'A', 'A',
        "{\"asd\":\"sdf\"}"
        , 13, 1,
        ""
        , 0
    },
    {
        "y_object_duplicated_key", 'y', 'A', 'A',
        "{\"a\":\"b\",\"a\":\"c\"}"
        , 17, 1,
        ""
        , 0
    },
    {
        "y_object_duplicated_key_and_value", 'y', 'A', 'A',
        "{\"a\":\"b\",\"a\":\"b\"}"
        , 17, 1,
        ""
        , 0
    },
    {
        "y_object_empty", 'y', 'A', 'A',
        "{}"
        , 2, 1,
        ""
        , 0
    },
    {
        "y_object_empty_key", 'y', 'A', 'A',
        "{\"\":0}"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_object_escaped_null_in_key", 'y', 'A', 'A',
        "{\"foo\\u0000bar\": 42}"
        , 20, 1,
        ""
        , 0
    },
    {
        "y_object_extreme_numbers", 'y', 'A', 'A',
        "{ \"min\": -1.0e+28, \"max\": 1.0e+28 }"
        , 35, 1,
        ""
        , 0
    },
    {
        "y_object_long_strings", 'y', 'A', 'A',
        "{\"x\":[{\"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}], \"i"
        "d\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}"
        , 108, 1,
        ""
        , 0
    },
    {
        "y_object_simple", 'y', 'A', 'A',
        "{\"a\":[]}"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_object_string_unicode", 'y', 'A', 'A',
        "{\"title\":\"\\u041f\\u043e\\u043b\\u0442\\u043e\\u0440\\u0430 \\u04"
        "17\\u0435\\u043c\\u043b\\u0435\\u043a\\u043e\\u043f\\u0430\" }"
        , 110, 1,
        ""
        , 0
    },
    {
        "y_object_with_newlines", 'y', 'A', 'A',
        "{\012\"a\": \"b\"\012}"
        , 12, 1,
        ""
        , 0
    },
    {
        "y_string_1_2_3_bytes_UTF-8_sequences", 'y', 'A', 'A',
        "[\"\\u0060\\u012a\\u12AB\"]"
        , 22, 1,
        ""
        , 0
    },
    {
        "y_string_accepted_surrogate_pair", 'y', 'A', 'A',
        "[\"\\uD801\\udc37\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "y_string_accepted_surrogate_pairs", 'y', 'A', 'A',
        "[\"\\ud83d\\ude39\\ud83d\\udc8d\"]"
        , 28, 1,
        ""
        , 0
    },
    {
        "y_string_allowed_escapes", 'y', 'A', 'A',
        "[\"\\\"\\\\\\/\\b\\f\\n\\r\\t\"]"
        , 20, 1,
        ""
        , 0
    },
    {
        "y_string_backslash_and_u_escaped_zero", 'y', 'A', 'A',
        "[\"\\\\u0000\"]"
        , 11, 1,
        ""
        , 0
    },
    {
        "y_string_backslash_doublequotes", 'y', 'A', 'A',
        "[\"\\\"\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_string_comments", 'y', 'A', 'A',
        "[\"a/*b*/c/*d//e\"]"
        , 17, 1,
        ""
        , 0
    },
    {
        "y_string_double_escape_a", 'y', 'A', 'A',
        "[\"\\\\a\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_double_escape_n", 'y', 'A', 'A',
        "[\"\\\\n\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_escaped_control_character", 'y', 'A', 'A',
        "[\"\\u0012\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_escaped_noncharacter", 'y', 'A', 'A',
        "[\"\\uFFFF\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_in_array", 'y', 'A', 'A',
        "[\"asd\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_in_array_with_leading_space", 'y', 'A', 'A',
        "[ \"asd\"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_string_last_surrogates_1_and_2", 'y', 'A', 'A',
        "[\"\\uDBFF\\uDFFF\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "y_string_nbsp_uescaped", 'y', 'A', 'A',
        "[\"new\\u00A0line\"]"
        , 17, 1,
        ""
        , 0
    },
    {
        "y_string_nonCharacterInUTF-8_U+10FFFF", 'y', 'A', 'A',
        "[\"\364\217\277\277\"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_string_nonCharacterInUTF-8_U+FFFF", 'y', 'A', 'A',
        "[\"\357\277\277\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_null_escape", 'y', 'A', 'A',
        "[\"\\u0000\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_one-byte-utf-8", 'y', 'A', 'A',
        "[\"\\u002c\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_pi", 'y', 'A', 'A',
        "[\"\317\200\"]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_string_reservedCharacterInUTF-8_U+1BFFF", 'y', 'A', 'A',
        "[\"\360\233\277\277\"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_string_simple_ascii", 'y', 'A', 'A',
        "[\"asd \"]"
        , 8, 1,
        ""
        , 0
    },
    {
        "y_string_space", 'y', 'A', 'A',
        "\" \""
        , 3, 1,
        ""
        , 0
    },
    {
        "y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF", 'y', 'A', 'A',
        "[\"\\uD834\\uDd1e\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "y_string_three-byte-utf-8", 'y', 'A', 'A',
        "[\"\\u0821\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_two-byte-utf-8", 'y', 'A', 'A',
        "[\"\\u0123\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_u+2028_line_sep", 'y', 'A', 'A',
        "[\"\342\200\250\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_u+2029_par_sep", 'y', 'A', 'A',
        "[\"\342\200\251\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_string_uEscape", 'y', 'A', 'A',
        "[\"\\u0061\\u30af\\u30EA\\u30b9\"]"
        , 28, 1,
        ""
        , 0
    },
    {
        "y_string_uescaped_newline", 'y', 'A', 'A',
        "[\"new\\u000Aline\"]"
        , 17, 1,
        ""
        , 0
    },
    {
        "y_string_unescaped_char_delete", 'y', 'A', 'A',
        "[\"\177\"]"
        , 5, 1,
        ""
        , 0
    },
    {
        "y_string_unicode", 'y', 'A', 'A',
        "[\"\\uA66D\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicodeEscapedBackslash", 'y', 'A', 'A',
        "[\"\\u005C\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_2", 'y', 'A', 'A',
        "[\"\342\215\202\343\210\264\342\215\202\"]"
        , 13, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+10FFFE_nonchar", 'y', 'A', 'A',
        "[\"\\uDBFF\\uDFFE\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+1FFFE_nonchar", 'y', 'A', 'A',
        "[\"\\uD83F\\uDFFE\"]"
        , 16, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+200B_ZERO_WIDTH_SPACE", 'y', 'A', 'A',
        "[\"\\u200B\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+2064_invisible_plus", 'y', 'A', 'A',
        "[\"\\u2064\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+FDD0_nonchar", 'y', 'A', 'A',
        "[\"\\uFDD0\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_U+FFFE_nonchar", 'y', 'A', 'A',
        "[\"\\uFFFE\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_unicode_escaped_double_quote", 'y', 'A', 'A',
        "[\"\\u0022\"]"
        , 10, 1,
        ""
        , 0
    },
    {
        "y_string_utf8", 'y', 'A', 'A',
        "[\"\342\202\254\360\235\204\236\"]"
        , 11, 1,
        ""
        , 0
    },
    {
        "y_string_with_del_character", 'y', 'A', 'A',
        "[\"a\177a\"]"
        , 7, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_false", 'y', 'A', 'A',
        "false"
        , 5, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_int", 'y', 'N', 'N',
        "42"
        , 2, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_negative_real", 'y', 'N', 'N',
        "-0.1"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_null", 'y', 'A', 'A',
        "null"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_string", 'y', 'A', 'A',
        "\"asd\""
        , 5, 1,
        ""
        , 0
    },
    {
        "y_structure_lonely_true", 'y', 'A', 'A',
        "true"
        , 4, 1,
        ""
        , 0
    },
    {
        "y_structure_string_empty", 'y', 'A', 'A',
        "\"\""
        , 2, 1,
        ""
        , 0
    },
    {
        "y_structure_trailing_newline", 'y', 'A', 'A',
        "[\"a\"]\012"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_structure_true_in_array", 'y', 'A', 'A',
        "[true]"
        , 6, 1,
        ""
        , 0
    },
    {
        "y_structure_whitespace_array", 'y', 'A', 'A',
        " [] "
        , 4, 1,
        ""
        , 0
    },
};

#endif
